# Generated by Django 4.1.7 on 2023-03-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(db_index=True, max_length=100, verbose_name='Название каталога меню')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Каталог меню',
                'verbose_name_plural': 'Каталог меню',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(db_index=True, max_length=100, verbose_name='Название меню')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL меню')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.catalogmenu', verbose_name='Каталог меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PunktMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkt_name', models.CharField(db_index=True, max_length=100, verbose_name='Название пункта меню')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL пункта меню')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('men', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PodPunktMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podpunkt_name', models.CharField(max_length=100, verbose_name='Название подпункта меню')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL подпункта')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('punktmen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.punktmenu', verbose_name='Пункт меню')),
            ],
            options={
                'verbose_name': 'Подпункт меню',
                'verbose_name_plural': 'Подпункты меню',
                'ordering': ['id'],
            },
        ),
    ]
